### PR TITLE
feat: Add The Project Introduction

### PR DESCRIPTION
**Pull request by DoWake**
If this PR is related to coding or code translation, please fill out the checklist and paste the console outputs to the PR.

- [x] I've tested the code and ensured the outputs are the same as the outputs of reference codes.
- [x] I've checked the codes (formatting, comments, indentation, file header, etc) carefully.

### CODE REVIEW

**Comment by w623377** [comment]
666

**Comment by DoWake** [comment]
### 项目介绍

> 1212

`12312378eqwhjkehqwue212`

@w623377 
```java
import java.util.*;
public class Main {
	public static void main(String[] args) {
		Queue<Integer> queue = new LinkedList<>();

        /* 元素入队 */
        queue.offer(1);
        queue.offer(3);
        queue.offer(2);
        queue.offer(5);
        queue.offer(4);
        System.out.println("队列 queue = " + queue);
	}
}

```

**Comment by DoWake** [comment]
### 项目介绍

> 1212

`12312378eqwhjkehqwue212`

@w623377 
```java
import java.util.*;
public class Main {
	public static void main(String[] args) {
		Queue<Integer> queue = new LinkedList<>();

        /* 元素入队 */
        queue.offer(1);
        queue.offer(3);
        queue.offer(2);
        queue.offer(5);
        queue.offer(4);
        System.out.println("队列 queue = " + queue);
	}
}

```

**Comment by DoWake** [comment]
/
下载

**Pull request merged**
